[masters]
et-k8s-m1 ansible_host=10.10.7.207 hostname=et-k8s-m1

[workers]
et-k8s-w1 ansible_host=10.10.7.208 hostname=et-k8s-w1

[k8s_nodes:children]
masters
workers

[all:vars]
ansible_user=bbg
ansible_password=1qaz@WSX
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become=yes
ansible_become_pass=1qaz@WSX

k8s_version=1.35.1-1.1
k8s_image_version=v1.35.1
cluster_name=cka-k8s
control_plane_endpoint=10.10.7.207:6443
pod_network_cidr=10.244.0.0/16
service_cidr=10.96.0.0/16
containerd_version=2.2.1
calico_version=v3.31.4