[masters]
bbg-erict-k8s-m1 ansible_host=192.168.1.115 hostname=bbg-erict-k8s-m1

[workers]
bbg-erict-k8s-w1 ansible_host=192.168.1.116 hostname=bbg-erict-k8s-w1

[k8s_nodes:children]
masters
workers

[all:vars]
ansible_user=bbg
ansible_password=1qaz@WSX
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become=yes
ansible_become_pass=1qaz@WSX

k8s_version=1.36.3-1.1
k8s_image_version=v1.36.3
cluster_name=cka-k8s
control_plane_endpoint=192.168.1.115:6443
# API server advertise/host IP. Leave unset to auto-detect the master's default IP.
# apiserver_advertise_address=192.168.1.115
pod_network_cidr=10.244.0.0/16
service_cidr=10.96.0.0/16
containerd_version=2.3.3
runc_version=v1.5.1
cni_plugins_version=v1.9.1
cilium_version=v1.19.6
helm_version=v4.2.3
