---
- name: Ultra Simple SSH Setup
  hosts: all
  become: true
  vars:
    ssh_key_path: "{{ ansible_ssh_private_key_file | default('~/.ssh/id_rsa') }}"

  pre_tasks:
    - name: Ensure sshpass is installed (Debian/Ubuntu)
      apt:
        name: sshpass
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure sshpass is installed (RedHat/CentOS)
      yum:
        name: sshpass
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure sshpass is installed (Fedora)
      dnf:
        name: sshpass
        state: present
      when: ansible_distribution == "Fedora"

  tasks:
    - name: Generate SSH key if not exists
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_path }}"
        type: rsa
        size: 4096
        comment: "admin@{{ ansible_hostname }}"
        state: present
      delegate_to: localhost
      run_once: true

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Ensure hostname in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ inventory_hostname }}"
        state: present

    - name: Copy SSH key to user
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', ssh_key_path + '.pub') }}"

    - name: Copy SSH key to root
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', ssh_key_path + '.pub') }}"

    - name: Verify user passwordless login
      command: echo "User OK"
      become: false

    - name: Verify root passwordless login
      command: echo "Root OK"
      become: false
      remote_user: root